### ISSUE TITLE
eslint --fix 格式化特定的 less 报错

### ISSUE THREAD

**Issue by Yuan-ZW** [antfu/eslint-plugin-antfu#36]
### Describe the bug

当使用 `@antfu/eslint-config` 并开启 `formatters: true` 时, 对以下代码执行 `eslint --fix` 会报错:
```vue
<template>
  <div>test</div>
</template>

<style lang="less" scoped>
.a {
.b {
  .c {
    padding: 1rem;
  }
}
  
}
</style>
```
**注**: 其中倒数第三行的空行包含**两个空格**
执行 `eslint --fix` 报错:
```prolog
> eslint --fix test.vue


Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Cannot read properties of undefined (reading 'range')
    at attemptFix (D:\YZW\Desktop\minimal-demo\node_modules\.pnpm\eslint@9.15.0\node_modules\eslint\lib\linter\source-code-fixer.js:88:27)
    at SourceCodeFixer.applyFixes (D:\YZW\Desktop\minimal-demo\node_modules\.pnpm\eslint@9.15.0\node_modules\eslint\lib\linter\source-code-fixer.js:123:17)
    at Linter.verifyAndFix (D:\YZW\Desktop\minimal-demo\node_modules\.pnpm\eslint@9.15.0\node_modules\eslint\lib\linter\linter.js:2329:43)
    at verifyText (D:\YZW\Desktop\minimal-demo\node_modules\.pnpm\eslint@9.15.0\node_modules\eslint\lib\eslint\eslint.js:329:48)
    at D:\YZW\Desktop\minimal-demo\node_modules\.pnpm\eslint@9.15.0\node_modules\eslint\lib\eslint\eslint.js:810:40
 ELIFECYCLE  Command failed with exit code 2.
```

---
同时, 针对 `less` 文件:
```less
.a {
.b {
  .c {
    padding: 1rem;
  }
}
  
}
```
**注**: 同样倒数第二行的空行也包含**两个空格**
执行 `eslint --fix` 之后 `less` 文件变成:
```less
.a {
  .b {
    .c {
      padding: 1rem;
    }

}
```
同时报错:
```prolog
> eslint --fix test.less


D:\YZW\Desktop\minimal-demo\test.less
  1:2  error  Parsing error: CssSyntaxError: Unclosed block  format/prettier

✖ 1 problem (1 error, 0 warnings)

 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

https://github.com/Yuan-ZW/eslint-minimal-example

### System Info

```Shell
System:
    OS: Windows 11 10.0.26120
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12450H
    Memory: 3.32 GB / 15.71 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.26100.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by ntnyq** [comment]
Related: https://github.com/antfu/eslint-config/issues/607

And you should report this issue to https://github.com/antfu/eslint-config
